name: Deploy Express App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Load environment (IMPORTANT FIX)
          source ~/.bashrc
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Go to project folder
          cd /home/ubuntu/backend/Crud-application-express-js
          
          # Pull latest code
          git pull origin main
          
          # Install dependencies
          npm install --production
          
          # Restart app using name (safer than ID)
          pm2 restart index
          
          # Show status
          pm2 status